In [1]:
import torch
import numpy as np

In [2]:
# Tensor initialization
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
# Bridging to/from numpy
np_data = np.array(data)
x_np = torch.tensor(np_data)

In [5]:
# From another tensor
x_ones = torch.ones_like(x_data)
print(f"Ones tensor: \n {x_ones}\n")
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random tensor: \n {x_rand}\n")

Ones tensor: 
 tensor([[1, 1],
        [1, 1]])

Random tensor: 
 tensor([[0.3624, 0.5809],
        [0.8929, 0.5550]])



In [6]:
#With dimensionality tuple
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(ones_tensor)
print(rand_tensor)
print(zeros_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.1117, 0.9564, 0.2316],
        [0.9554, 0.5912, 0.0590]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Tensor Attributes

In [7]:

tensor = torch.rand(3,4)
print(f"Tensor is of shape: {tensor.shape}")
print(f"Tensor if of type: {tensor.dtype}")
print(f"Tensor is stored on: {tensor.device}")

Tensor is of shape: torch.Size([3, 4])
Tensor if of type: torch.float32
Tensor is stored on: cpu


### Tensor Operations
There are tons of tensor operations, which can be found here: https://pytorch.org/docs/stable/torch.html

In [8]:
# Move tensor to GPU if possible (in my case it is not. Doing it on a macbook)
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [9]:
# Numpy like indexing
tensor = torch.ones(5,5)
tensor[:,3] = 0
print(tensor)

tensor([[1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.]])


In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim=0) #torch.stack is slightly different
print(t1)

tensor([[1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.],
        [1., 1., 1., 0., 1.]])


In [11]:
t2 = torch.stack([tensor, tensor, tensor], dim=0)
print(t2)

tensor([[[1., 1., 1., 0., 1.],
         [1., 1., 1., 0., 1.],
         [1., 1., 1., 0., 1.],
         [1., 1., 1., 0., 1.],
         [1., 1., 1., 0., 1.]],

        [[1., 1., 1., 0., 1.],
         [1., 1., 1., 0., 1.],
         [1., 1., 1., 0., 1.],
         [1., 1., 1., 0., 1.],
         [1., 1., 1., 0., 1.]],

        [[1., 1., 1., 0., 1.],
         [1., 1., 1., 0., 1.],
         [1., 1., 1., 0., 1.],
         [1., 1., 1., 0., 1.],
         [1., 1., 1., 0., 1.]]])


In [12]:
#Multiplying tensors
#Element wise multiplying
tensor = torch.rand((2,3), dtype=float)
print(tensor)
print(f"\ntensor.mul(tensor): \n{tensor.mul(tensor)})\n")
print(f"tensor*tensor: \n{tensor*tensor})")

tensor([[0.0385, 0.6992, 0.9481],
        [0.0635, 0.1001, 0.3109]], dtype=torch.float64)

tensor.mul(tensor): 
tensor([[0.0015, 0.4889, 0.8990],
        [0.0040, 0.0100, 0.0966]], dtype=torch.float64))

tensor*tensor: 
tensor([[0.0015, 0.4889, 0.8990],
        [0.0040, 0.0100, 0.0966]], dtype=torch.float64))


In [13]:
#Matrix multiplication of two tensors
print(f"tensor.matmul(tensor.T):\n {tensor.matmul(tensor.T)}")
#Alternative syntax
print(f"\ntensor @ tensor.T: \n {tensor @ tensor.T}")

tensor.matmul(tensor.T):
 tensor([[1.3894, 0.3671],
        [0.3671, 0.1107]], dtype=torch.float64)

tensor @ tensor.T: 
 tensor([[1.3894, 0.3671],
        [0.3671, 0.1107]], dtype=torch.float64)


In [14]:
# Operations with _ in suffix will change the variable in-place
print(tensor,"\n")
tensor.add_(5)
print(tensor)

#NOTE: In-place operations save some memory, but can be problematic when 
#computing derivatives because of an immediate loss of history. 
#Hence, their use is discouraged.

tensor([[0.0385, 0.6992, 0.9481],
        [0.0635, 0.1001, 0.3109]], dtype=torch.float64) 

tensor([[5.0385, 5.6992, 5.9481],
        [5.0635, 5.1001, 5.3109]], dtype=torch.float64)


### Bridge with Numpy

In [26]:
#Tensors on the CPU and NumPy arrays can share their underlying memory locations, 
#and changing one will change the other.
t = torch.ones(5)
print(t)
n = t.numpy()

t.add_(3)
print(f"t: {t}")
print(f"n: {n}")

tensor([1., 1., 1., 1., 1.])
t: tensor([4., 4., 4., 4., 4.])
n: [4. 4. 4. 4. 4.]


In [30]:
n = np.ones(3)
t = torch.from_numpy(n)
#Changes in one will affect the other
np.add(n, 1, out=n)
print(n)
print(t)
t.add_(1)
print(n)
print(t)

[2. 2. 2.]
tensor([2., 2., 2.], dtype=torch.float64)
[3. 3. 3.]
tensor([3., 3., 3.], dtype=torch.float64)


[3. 3. 3.]
